### PR TITLE
[Feat] - Adding Theme Switch to Page#3

### LINKED ISSUE #3: [FEAT]:  Add Theme Switch
Adding a theme switch
Mainly Dark and White mode
But it would be great to have multiple color options for the theme

### PR DESCRIPTION
**Pull request by 0nikhilkumar**
Sir I'm a hacktoberfest'23 contributor.
Please mark the label of "HACKTOBERFEST-ACCEPTED" So I am eligible for counted 1PR accepted.

Adding Theme switch for change into dark mode to white mode & vice-versa.

feat #3 

**Dark Mode** - 
dark Mode

**White Mode** -
white Mode

Add a theme change button 

How should this be tested?
1. Go on home page
2. See on top-right of the page

### CODE REVIEW

**Comment by 0nikhilkumar** [comment]
Sir please merge it if you like my work and please mark the label "hacktoberfest-accepted" @Vyvy-vi @dishant0406 @fykaa @Spyder15

**Comment by Vyvy-vi** [comment]
this project isn't taking part in hacktoberfest...

**Comment by 0nikhilkumar** [comment]
> this project isn't taking part in hacktoberfest...

sir why, but your repo is taking part in hacktoberfest2023

**Comment by 0nikhilkumar** [comment]
and sir please mark "hacktoberfest-accepted" label on last pr that you merge already please sir.
@Vyvy-vi @dishant0406 @Spyder15 @fykaa

**Pull request closed without merging**
