### PR TITLE
[Enhancement]: Separated links to another data file #2

### PR DESCRIPTION
**Pull request by 0nikhilkumar**
The links is separated to the data.js file.

enhancement #2 

How should this be tested?
1. Go to code folder
2.  there is new file "data.js" in src folder.
data

3. See Like this in the code
show links

### CODE REVIEW

**Review by Vyvy-vi — CHANGES_REQUESTED** [review]
Looks Good To Me!

Why are there both `package-lock.json` and `yarn.lock` over here?
Kindly delete the package-lock.json file...

**Comment by 0nikhilkumar** [comment]
please check it out, It is deleted.

**Comment by 0nikhilkumar** [comment]
Now its look good @Vyvy-vi

**Comment by 0nikhilkumar** [comment]
**### _Sir Please merge this PR as You Like My work_** @fykaa  @Vyvy-vi @dishant0406 @Spyder15

**Comment by 0nikhilkumar** [comment]
Sir I'm a hacktoberfest'23 contributor. 
Please mark the label of "HACKTOBERFEST-ACCEPTED" So I am eligible for counted 1PR accepted.

@Vyvy-vi @Spyder15 @dishant0406 @fykaa

**Comment by 0nikhilkumar** [comment]
sir I am doing an contribution, Which is great but You haven't mark "hacktoberfest-accepted" label on this closed pr. Please mark the label and this is counted to hacktoberfest23 and your repo is also participated in hacktoberfest23. Please Please Please sir
@Vyvy-vi @Spyder15 @dishant0406 @fykaa

**Pull request merged**
